services:
  postgres:
    image: postgres:17
    container_name: alpha_chat_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alpha_chat

    ports:
      - "5432:5432"

    volumes:
      - ./schemas/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
